# Generated by Django 3.0.5 on 2023-11-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_content', models.CharField(blank=True, max_length=100, null=True)),
                ('blog_type', models.CharField(default='Professional', max_length=100)),
                ('reward', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('user_query', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
